In [8]:
from sklearn import preprocessing
labels=['setosa','versicolor','virginica']
encoder=preprocessing.LabelEncoder()
encoder.fit(labels)
transformed_data=encoder.transform(['setosa','versicolor','virginica','setosa','setosa'])
print(transformed_data)

array([0, 1, 2, 0, 0], dtype=int64)

In [18]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = np.array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([np.argmax([0,0,1])])
print(inverted)
print(np.argmax([0,0,1]))

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
['warm']
2


In [29]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
X = pd.read_csv('titanic_data.csv')
X.head(3)
X = X.select_dtypes(include=[object])
X.head(3)
le = preprocessing.LabelEncoder()
X_2 = X.apply(le.fit_transform)
X_2.head()
enc = preprocessing.OneHotEncoder()

# 2. FIT
enc.fit(X_2)

# 3. Transform
onehotlabels = enc.transform(X_2).toarray()
onehotlabels

TypeError: ('unorderable types: float() > str()', 'occurred at index Cabin')