In [53]:
from sklearn import datasets
import numpy as np
iris = datasets.load_iris()
iris_X = iris.data

In [54]:
iris_X [:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [55]:
masking_array = np.random.binomial(1, .25, 
                     iris_X.shape).astype(bool)

In [56]:
masking_array

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [ True, False,  True,  True],
       [False,  True, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False,  True,  True],
       [False, False,  True, False],
       [False,  True, False,  True],
       [False,  True, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
 

In [57]:
iris_X[masking_array] = np.nan
iris_X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  nan,  1.4,  0.2],
       [ nan,  3.9,  nan,  nan],
       [ 4.6,  nan,  1.4,  0.3],
       [ 5. ,  nan,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ nan,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  nan,  nan],
       [ 4.8,  3. ,  nan,  0.1],
       [ 4.3,  nan,  1.1,  nan],
       [ 5.8,  nan,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  nan],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  nan,  nan],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  nan],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  nan,  0.2],
       [ 5.2,  3.4,  1.4,  nan],
       [ 4.7,  nan,  1.6,  0.2],
       [ 4

In [58]:
from sklearn import preprocessing
impute = preprocessing.Imputer()
iris_X_prime = impute.fit_transform(iris_X)
iris_X_prime[:5]

array([[ 5.1       ,  3.5       ,  1.4       ,  0.2       ],
       [ 4.9       ,  3.        ,  1.4       ,  0.2       ],
       [ 4.7       ,  3.2       ,  1.3       ,  0.2       ],
       [ 4.6       ,  3.1       ,  1.5       ,  0.2       ],
       [ 5.        ,  3.06696429,  1.4       ,  0.2       ]])

In [67]:
#replace all NaN with -1
iris_X[np.isnan(iris_X)] = -1
iris_X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. , -1. ,  1.4,  0.2],
       [-1. ,  3.9, -1. , -1. ],
       [ 4.6, -1. ,  1.4,  0.3],
       [ 5. , -1. ,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [-1. ,  3.7,  1.5,  0.2],
       [ 4.8,  3.4, -1. , -1. ],
       [ 4.8,  3. , -1. ,  0.1],
       [ 4.3, -1. ,  1.1, -1. ],
       [ 5.8, -1. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5, -1. ],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8, -1. , -1. ],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6, -1. ],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5, -1. ,  0.2],
       [ 5.2,  3.4,  1.4, -1. ],
       [ 4.7, -1. ,  1.6,  0.2],
       [ 4

In [71]:
data=np.array([[1,3,np.nan],[2,np.nan,8],[3,np.nan,1],[np.nan,2,1]])
from sklearn.preprocessing import Imputer
data

array([[  1.,   3.,  nan],
       [  2.,  nan,   8.],
       [  3.,  nan,   1.],
       [ nan,   2.,   1.]])

In [70]:
print('Mean strategy')
imp = Imputer(strategy='mean')
print(imp.fit_transform(data))

Mean strategy
[[ 1.          3.          3.33333333]
 [ 2.          2.5         8.        ]
 [ 3.          2.5         1.        ]
 [ 2.          2.          1.        ]]


In [69]:
print('Median strategy')
imp = Imputer(strategy='median')
print(imp.fit_transform(data))

Median strategy
[[ 1.   3.   1. ]
 [ 2.   2.5  8. ]
 [ 3.   2.5  1. ]
 [ 2.   2.   1. ]]


In [68]:
print('Mode strategy')
imp = Imputer(strategy='most_frequent')
print(imp.fit_transform(data))

Mode strategy
[[ 1.  3.  1.]
 [ 2.  2.  8.]
 [ 3.  2.  1.]
 [ 1.  2.  1.]]
