In [3]:
from sklearn import preprocessing
import numpy as np 

data = np.array([[2.2, 5.9, -1.8], [5.4, -3.2, -5.1], [-1.9, 4.2, 3.2]])
data

array([[ 2.2,  5.9, -1.8],
       [ 5.4, -3.2, -5.1],
       [-1.9,  4.2,  3.2]])

In [5]:
minmax_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
data_minmax = minmax_scaler.fit_transform(data)
print('MinMaxScaler applied on the data:\n', data_minmax)

MinMaxScaler applied on the data:
 [[ 0.56164384  1.          0.39759036]
 [ 1.          0.          0.        ]
 [ 0.          0.81318681  1.        ]]


In [9]:
ss = preprocessing.StandardScaler()
data_ss = ss.fit_transform(data)
print('StandardScaler applied on the data:\n', data_ss)

StandardScaler applied on the data:
 [[ 0.10040991  0.91127074 -0.16607709]
 [ 1.171449   -1.39221918 -1.1332319 ]
 [-1.27185891  0.48094844  1.29930899]]


In [10]:
rs = preprocessing.RobustScaler()
data_rs = rs.fit_transform(data)
print('RobustScaler applied on the data:\n', data_rs)

RobustScaler applied on the data:
 [[ 0.          0.37362637  0.        ]
 [ 0.87671233 -1.62637363 -0.79518072]
 [-1.12328767  0.          1.20481928]]


In [11]:
rs = preprocessing.Normalizer()
data_normalizer = rs.fit_transform(data)
print('Normalizer applied on the data:\n', data_normalizer)

Normalizer applied on the data:
 [[ 0.3359268   0.90089461 -0.2748492 ]
 [ 0.6676851  -0.39566524 -0.63059148]
 [-0.33858465  0.74845029  0.57024784]]


Binarization

In [12]:
bindata = preprocessing.Binarizer(threshold=1.5).transform(data)
print('Binarized data:\n\n', bindata)

Binarized data:

 [[ 1.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  1.]]


Mean Removal

In [13]:
print('Mean (before)= ', data.mean(axis=0))
print('Standard Deviation (before)= ', data.std(axis=0))
scaled_data = preprocessing.scale(data)
print('Mean (after)= ', scaled_data.mean(axis=0))
print('Standard Deviation (after)= ', scaled_data.std(axis=0))

Mean (before)=  [ 1.9         2.3        -1.23333333]
Standard Deviation (before)=  [ 2.98775278  3.95052739  3.41207008]
Mean (after)=  [  0.00000000e+00   0.00000000e+00   7.40148683e-17]
Standard Deviation (after)=  [ 1.  1.  1.]
